---
resources:
- name: cicd-repo
  type: git
  source:
    uri: https://github.com/lamar-frankie/iiab-cicd.git

- name: iiab
  type: git
  source:
    uri: https://github.com/iiab/iiab.git

- name: admin-console
  type: git
  source:
    uri: https://github.com/iiab/iiab-admin-console.git

- name: menu
  type: git
  source:
    uri: https://github.com/iiab/iiab-menu.git

- name: factory
  type: git
  source:
    uri: https://github.com/iiab/iiab-factory.git

jobs:
- name: Playbook Tests
  public: true
  plan:
  - get: cicd-repo
  - get: iiab
  - get: admin-console
  - get: menu
  - get: factory
  - task: Setup Test Environment
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: debian}
      inputs:
      - name: cicd-repo
      - name: iiab
      - name: admin-console
      - name: menu
      - name: factory
      outputs:
      - name: /opt/iiab
      run:
        path: sh
        args:
        - -exc
        - |
          chmod -R 755 *
          ./cicd-repo/setup.sh

#- name: Setup Ansible
#  public: true
#  plan: get /opt/iiab
#  - get: /opt/isv
#  - task: Configure Ansible
#    config:
#    platform: linux
#    image_resource:
#    type: docker-image
#    source: { repository: debian}
#    inputs:
#    - name: /opt/iiab
#    outputs:
#    -name: /opt/iiab
#    run:
#      path: sh
#      args:
#      - -exc
#      - |
#        cd /opt/iiab/iiab/scripts/
#        ./ansible
