---
resources:
- name: code-repo
  type: git
  source:
    uri: https://github.com/lamar-frankie/iiab.git

- name: cicd-repo
  type: git
  source:
    uri: https://github.com/lamar-frankie/iiab-cicd.git

jobs:
- name: Playbook Tests
  public: true
  plan:
  - get: cicd-repo
  - get: code-repo
  - task: hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: debian}
      inputs:
      - name: code-repo
      - name: cicd-repo
      run:
        path: chmod -R 777
        args: *